"""Índice de ECO e lista FIXA de H2 por nota (Folha -Q §2). Gera ECO-Q_plano.json (sem as passadas)."""
import json

BLOCOS = {
 "I. MICROECONOMIA": [
  ("01", "🦋 Microeconomia: fundamentos, CPP, demanda e oferta, bens, equilíbrio",
   ["🧭 Fundamentos e escassez", "📐 Curva de possibilidades de produção", "📈 Demanda: determinantes e deslocamentos",
    "🏭 Oferta: determinantes e deslocamentos", "🏷️ Classificação dos bens", "⚖️ Equilíbrio e estática comparativa"]),
  ("02", "🍰 Elasticidades",
   ["📐 Elasticidade-preço da demanda", "💰 Elasticidade, receita e gasto", "🔗 Elasticidade-renda e cruzada",
    "🏭 Elasticidade da oferta", "⏳ Determinantes e prazos"]),
  ("03", "🍫 Intervenções do Estado na economia e economia do bem-estar",
   ["😊 Excedentes e eficiência", "💸 Tributos: incidência e peso morto", "🧾 Subsídios",
    "🚧 Preços máximos e mínimos", "🧮 Cotas e outras intervenções"]),
  ("04", "🍇 Teoria do consumidor, curvas preço-consumo e Engel, efeitos renda e substituição",
   ["🧠 Preferências e axiomas", "🎯 Utilidade e curvas de indiferença", "💵 Restrição orçamentária",
    "⚖️ Escolha ótima do consumidor", "📊 Demanda individual e de mercado"]),
  ("04-A", "🤑 Preço-consumo, Engel e efeitos renda/substituição",
   ["📈 Curva preço-consumo", "📉 Curva renda-consumo e Engel", "🔀 Efeitos renda e substituição",
    "🥔 Bens inferiores e de Giffen", "🧮 Slutsky e Hicks"]),
  ("05", "☂️ Teoria da firma I (produção — isoquanta)",
   ["🏭 Função de produção e curto prazo", "📉 Produto marginal e rendimentos", "🗺️ Isoquantas e TMST",
    "📏 Rendimentos de escala"]),
  ("06", "💧 Teoria da firma II (custos — isocusto)",
   ["💰 Custos de curto prazo", "📈 Custos de longo prazo e escala", "⚖️ Isocusto e combinação ótima",
    "🧾 Custo econômico × contábil"]),
  ("07", "🌈 Estruturas de mercado (panorama)", ["🗺️ Comparação entre estruturas"]),
  ("07-A", "🌈 Concorrência perfeita",
   ["📐 Hipóteses e maximização de lucro", "⏱️ Curto prazo: oferta da firma", "⏳ Longo prazo e entrada/saída"]),
  ("08", "🍒 Monopólio e monopsônio",
   ["👑 Equilíbrio do monopólio", "📊 Markup, elasticidade e poder de mercado", "🎟️ Discriminação de preços",
    "🏛️ Monopólio natural e regulação", "🛒 Monopsônio"]),
  ("09", "⚔️ Concorrência monopolística", ["🧩 Modelo de Chamberlin"]),
  ("10", "🦑 Oligopólios",
   ["🧮 Cournot e Bertrand", "🥇 Stackelberg e liderança", "🤝 Cartel e conluio", "📏 Concentração e outras teorias"]),
  ("11", "🎲 Teoria dos jogos",
   ["♟️ Equilíbrio de Nash e dominância", "🔁 Jogos sequenciais e repetidos"]),
  ("12", "⚖️ Falhas de mercado, externalidades, tipos de bens e informações assimétricas",
   ["🌫️ Externalidades e Coase", "🏞️ Bens públicos e comuns", "🕵️ Informação assimétrica",
    "🏛️ Falhas de governo e regulação"]),
 ],
 "II. MACROECONOMIA E CONTAS NACIONAIS": [
  ("15", "⚡ Macroeconomia: panorama histórico (genealogia das ideias)", ["📜 Escolas do pensamento macroeconômico"]),
  ("16", "🌅 Conceitos básicos da teoria macroeconômica", ["🧭 Agregados e conceitos básicos"]),
  ("17", "🏺 Contas Nacionais",
   ["🔄 Identidades e óticas do produto", "📏 PIB, PNB, RNB e conceitos derivados", "💲 Preços de mercado × custo de fatores",
    "📊 Nominal × real e deflator", "🧾 SCN e tabelas"]),
  ("18", "🌊 Balanço de Pagamentos: estrutura e lançamentos",
   ["🏗️ Estrutura do BP (BPM6)", "✍️ Lançamentos", "🔗 BP e contas nacionais"]),
  ("19", "📿 Indicadores fiscais e de liquidez/solvência externa",
   ["💰 Resultados fiscais (NFSP)", "🌐 Indicadores externos"]),
 ],
 "III. MODELOS MACROECONÔMICOS E FLUTUAÇÕES": [
  ("25", "❄️ Modelo clássico de determinação da renda + TQM clássica (moeda e preços no longo prazo)",
   ["⚙️ Modelo clássico", "💵 Teoria quantitativa da moeda"]),
  ("26", "🏔️ Modelo keynesiano simples: demanda efetiva, multiplicador",
   ["📈 Demanda efetiva e cruz keynesiana", "✖️ Multiplicadores"]),
  ("27", "🎭 Modelo IS-LM (keynesiano generalizado / Hicks-Hansen)",
   ["📉 Curva IS", "📈 Curva LM", "🏦 Política fiscal e monetária", "🕳️ Casos extremos"]),
  ("28", "🌍 Modelo OA-DA", ["📈 Demanda agregada", "🏭 Oferta agregada e choques"]),
  ("29", "🐦 Curva de Phillips: inflação × desemprego, expectativas (adaptativas × racionais)",
   ["📉 Phillips original e aceleracionista", "🔮 Expectativas e NAIRU"]),
  ("30", "🧵 Síntese neoclássica e o debate macroeconômico contemporâneo", ["🗣️ Debate contemporâneo"]),
 ],
 "IV. ECONOMIA MONETÁRIA E SISTEMA FINANCEIRO": [
  ("35", "🎵 Economia monetária: moeda, criação, multiplicador, demanda por moeda",
   ["🪙 Funções e agregados monetários", "🏦 Criação de moeda e multiplicador", "📊 Demanda por moeda"]),
  ("36", "🌀 Banco Central e política monetária: funções, instrumentos, TQM operacional, senhoriagem e imposto inflacionário",
   ["🏛️ Funções do Banco Central", "🛠️ Instrumentos de política monetária", "💸 Senhoriagem e imposto inflacionário"]),
  ("37", "💥 Inflação: conceitos e correntes", ["🔥 Tipos e teorias da inflação"]),
  ("38", "🎯 Sistema de metas, ancoragem, forward guidance, regra de Taylor", ["🎯 Metas de inflação e regras"]),
  ("39", "🐉 Dominância fiscal, TFNP, coordenação fiscal-monetária", ["🐉 Dominância fiscal"]),
  ("40", "🚀 Políticas monetárias não convencionais: QE, tapering, QT, crises de 2008 e 2023",
   ["🖨️ QE, tapering e QT", "💥 Crises financeiras"]),
  ("41", "🏛️ Regulação do sistema bancário, financeiro e mercado de capitais, Basileia", ["🏛️ Regulação e Basileia"]),
  ("42", "💳 Bancos digitais, meios de pagamento, economia digital", ["💳 Pagamentos e economia digital"]),
 ],
 "V. SETOR PÚBLICO E POLÍTICA FISCAL": [
  ("47", "🌱 Setor público e funções do Estado, política fiscal, equivalência ricardiana",
   ["🏛️ Funções do Estado", "💸 Tributação: princípios e incidência", "📊 Política fiscal e multiplicadores",
    "🔮 Equivalência ricardiana"]),
  ("48", "🐘 Déficit e dívida públicos: financiamento, Wagner, Laffer, sustentabilidade, dívida/PIB",
   ["📏 Conceitos de déficit e dívida", "🧮 Financiamento e sustentabilidade", "📈 Wagner e Laffer"]),
  ("49", "🌕 Orçamento público: PPA/LDO/LOA, responsabilidade fiscal",
   ["📒 Ciclo orçamentário", "⚖️ Responsabilidade fiscal"]),
  ("50", "🌶️ Trajetória da dívida pública, teto de gastos, novo arcabouço fiscal",
   ["📈 Trajetória da dívida", "🧱 Regras fiscais: teto e arcabouço"]),
 ],
 "VI. CRESCIMENTO, DESENVOLVIMENTO E MERCADO DE TRABALHO": [
  ("55", "⭐ Teorias do consumo e investimento", ["🛒 Teorias do consumo", "🏗️ Teorias do investimento"]),
  ("56", "📈 Modelo de Solow: estado estacionário, regra de ouro, população e tecnologia",
   ["⚙️ Estado estacionário", "🥇 Regra de ouro", "👥 População, tecnologia e convergência"]),
  ("57", "💡 Crescimento endógeno (Romer, Lucas, Arrow), Schumpeter, Harrod-Domar", ["💡 Teorias do crescimento"]),
  ("58", "🌾 Desenvolvimento econômico", ["🌾 Teorias do desenvolvimento"]),
  ("59", "🐎 Mercado de trabalho, Lei de Okun", ["👷 Desemprego e mercado de trabalho", "📏 Lei de Okun"]),
  ("60", "🏭 Precarização, reforma trabalhista de 2017, conjuntura do trabalho", ["🏭 Conjuntura do trabalho"]),
 ],
 "VII. MACROECONOMIA ABERTA E FINANÇAS INTERNACIONAIS": [
  ("65", "🕰️ Sistema Financeiro Internacional: padrão-ouro, Bretton Woods, crises",
   ["🥇 Padrão-ouro", "🏦 Bretton Woods", "💥 Crises e pós-Bretton Woods"]),
  ("66", "💱 Câmbio e política cambial: regimes, nominal × real, PPC",
   ["💱 Regimes cambiais", "📏 Câmbio nominal × real e PPC", "📈 Determinantes do câmbio"]),
  ("67", "📘 Reservas internacionais e política cambial ativa", ["📘 Reservas e intervenção"]),
  ("68", "🧂 Poupança externa e crescimento econômico", ["🧂 Poupança externa", "🔗 Hiatos e restrição externa"]),
  ("69", "🔗 Relação câmbio-juros-inflação", ["🔗 Paridades e repasse cambial"]),
  ("70", "📍 Modelo IS-LM-BP (Mundell-Fleming)",
   ["📍 Curva BP e mobilidade de capital", "🔒 Câmbio fixo", "🌊 Câmbio flutuante"]),
 ],
 "VIII. COMÉRCIO E ECONOMIA INTERNACIONAL": [
  ("73", "⛵ Teorias clássicas e neoclássicas do comércio: Smith, Ricardo, Heckscher-Ohlin (H-O), teoremas, Leontief",
   ["⛵ Vantagens absolutas e comparativas", "🧪 Heckscher-Ohlin e teoremas", "❓ Paradoxo de Leontief e termos de troca"]),
  ("74", "🌎 Crítica da CEPAL: Prebisch, deterioração dos termos de troca", ["🌎 CEPAL e termos de troca"]),
  ("75", "🔬 Novas teorias do comércio: escala, concorrência imperfeita, comércio intraindustrial, intrafirma",
   ["🔬 Novas teorias do comércio"]),
  ("76", "⭐ Cadeias globais de valor: fluxos internacionais de bens e serviços", ["⭐ Cadeias globais de valor"]),
  ("77", "💼 Investimento internacional: portfólio × IED, internacionalização da produção", ["💼 IED e portfólio"]),
  ("78", "🌐 Globalização financeira e produtiva: volatilidade, riscos e vulnerabilidade externa",
   ["🌐 Globalização e vulnerabilidade"]),
  ("79", "🎪 Políticas comerciais e de comércio exterior: tarifas, cotas, subsídios",
   ["🧾 Tarifas", "🚫 Cotas e barreiras não tarifárias", "💰 Subsídios e defesa comercial", "🏛️ Política comercial e OMC"]),
 ],
 "IX. CONJUNTURA E ECONOMIA BRASILEIRA CONTEMPORÂNEA": [
  ("83", "🌋 Conjuntura econômica do Brasil", ["🌋 Conjuntura brasileira"]),
  ("84", "🌐 Conjuntura econômica internacional", ["🌐 Conjuntura internacional"]),
  ("85", "🧭 Raio-X e diagnósticos da economia brasileira: perspectivas em disputa", ["🧭 Diagnósticos em disputa"]),
 ],
}

if __name__ == "__main__":
    notas = []
    for bloco, ns in BLOCOS.items():
        for nid, tit, h2 in ns:
            notas.append({"id": nid, "titulo": tit, "bloco": bloco, "titulo_q": f"{nid}-1 - Obj.", "h2": h2})
    json.dump({"materia": "ECO", "versao_folha": "Q-v3", "notas": notas, "passadas": [],
               "teste_importacao": "pendente"}, open("ECO-Q_plano.json", "w"), ensure_ascii=False, indent=1)
    print(len(notas), "notas,", sum(len(n["h2"]) for n in notas), "H2")
